<?php

$cardSource = file_get_contents(__DIR__.'/../timesheetweek_card.php');
if ($cardSource === false) {
	fwrite(STDERR, "Unable to read the TimesheetWeek card.\n");
	exit(1);
}

$expectedBannerCall = "dol_banner_tab(\$object, 'id', \$linkback, 1, 'rowid', 'ref'";
if (strpos($cardSource, $expectedBannerCall) === false) {
	fwrite(STDERR, "The TimesheetWeek card navigation must use id and rowid.\n");
	exit(1);
}

if (strpos($cardSource, "\$id = GETPOSTINT('id');") === false) {
	fwrite(STDERR, "The TimesheetWeek card must read the id generated by its navigation arrows.\n");
	exit(1);
}

echo "Card navigation test passed.\n";
